refactor(impact analysis): 接口ID改为String，添加获取学者间引用关系的接口
NJU-SE-17-advanced-se/backend pull request #32
Opened 2020-10-13 07:35 UTC by Tdycwym

修改接口里的ID类型为String，新增学者间引用关系的接口
/citation/researchers
param:两个ID
返回Map<String, Integer> ID及引用次数

2020-10-13 10:29 UTC, HermitSun commented on task-impact-analysis/src/main/java/org/njuse17advancedse/taskimpactanalysis/controller/TaskImpactAnalysisController.java
> +  public int getHIndex(@PathVariable String id, @RequestParam String type) {
可以考虑增加一个`defaultValue`，可能并不是每一次请求都需要加type

2020-10-13 10:36 UTC, HermitSun commented on task-citation-analysis/src/main/java/org/njuse17advancedse/taskcitationanalysis/controller/TaskCitationAnalysisController.java
> +   * @param researcherId1
如果需要用 javadoc 风格的注释，最好能符合它的风格，否则还是用常规的注释比较好。
比如这里，`@param researcherId1` 后面少了描述。
其他几个地方同理。

2020-10-13 10:41 UTC, HermitSun requested changes
整体来说功能没有问题，但是有两个地方需要修改：
1. 引用分析没有写测试
2. 需要增加学者之间引用关系的接口，也就是返回某学者引用过的学者和某学者被哪些学者引用过的接口。目前的接口还只是论文之间的引用关系。

可能需要注意的地方：
1. 注释的问题，这个在comment里提到了
2. 可以考虑增加默认值，这个也在comment里提到了
2. 尽可能不要在一个pr里包含多个服务的内容，否则一个服务不符合要求，另一个符合要求的服务也得跟着一起被打回去，影响另一个服务的进度
4. 可以清理一下不用的实体

我的一个疑问：

`getResearcherQuoteNums`，也就是第一个学者每篇论文引用的第二个学者的论文数量这个接口是干啥的，给审稿人推荐服务用的吗，还是有什么别的用途？

2020-10-13 11:11 UTC, Tdycwym commented
暂时只添加了两个学者之间引用关系的接口 getResearcherQuoteNums这个方法感觉可能后边会用到吧

然后如果需要查看一个学者引用的所有其他学者的关系的话 我要新加一个接口 然后需要其他的服务

2020-10-13 11:21 UTC, HermitSun commented
> 暂时只添加了两个学者之间引用关系的接口 getResearcherQuoteNums这个方法感觉可能后边会用到吧
> 
> 然后如果需要查看一个学者引用的所有其他学者的关系的话 我要新加一个接口 然后需要其他的服务

这个还是要加一下的。

2020-10-14 04:42 UTC, Tdycwym commented
完成了测试和获取学者对其他学者引用关系的接口

2020-10-14 06:59 UTC, HermitSun requested changes
我觉得我可能没有说清楚，这个服务应该提供的接口包括：
1. 某个学者引用了哪些学者，返回`List<String>`
2. 某个学者被哪些学者引用，返回`List<String>`
3. 某个学者的论文分别引用了哪些论文，返回`Map<String, List<String>>`
4. 某个学者的论文分别被哪些论文引用，返回`Map<String, List<String>>`
5. 某个学者的论文分别引用了哪些学者，返回`Map<String, List<String>>`
6. 某个学者的论文分别被哪些学者引用，返回`Map<String, List<String>>`

看起来比较多，但主要是为了应对可能存在的变更情况。别的接口可以自由发挥。
回头URL可能需要重新改一下，不是非常REST。

2020-10-14 15:20 UTC, HermitSun requested changes
我认为应该有这些接口：
```java
  // 某个学者引用了哪些学者
  // 某个学者被哪些学者引用
  @GetMapping("/researcher/{id}")
  public List<String> getResearcherCitations(
          @PathVariable String id,
          @RequestParam String type){
    return new ArrayList<>();
  }

  // 某个学者的论文分别引用了哪些论文
  // 某个学者的论文分别被哪些论文引用
  @GetMapping("/researcher/{id}/papers")
  public Map<String, List<String>> getResearcherPapersCitations(
          @PathVariable String id,
          @RequestParam String type){
    return new HashMap<>();
  }

  // 某个学者的论文分别引用了哪些学者
  // 某个学者的论文分别被哪些学者引用
  @GetMapping("/researcher/{id}/papers/researchers")
  public Map<String, List<String>> getResearcherPapersCitedResearchers(
          @PathVariable String id,
          @RequestParam String type){
    return new HashMap<>();
  }

  // 某篇论文引用了哪些论文
  // 某篇论文被哪些论文引用
  @GetMapping("/paper/{id}")
  public List<String> getPaperCitations(
          @PathVariable String id,
          @RequestParam String type){
    return new ArrayList<>();
  }

  // 某篇论文引用了哪些学者
  // 某篇论文被哪些学者引用
  @GetMapping("/paper/{id}/researchers")
  public List<String> getPaperCitedResearchers(
          @PathVariable String id,
          @RequestParam String type){
    return new ArrayList<>();
  }
```
你可以视情况调整。

2020-10-15 03:15 UTC, HermitSun approved these changes
下次记得检查一下提交信息。
perf是优化性能，style才是调整格式。

2020-10-15 03:16 UTC, merged