Develop
NJU-SE-17-advanced-se/backend pull request #33
Opened 2020-10-14 04:44 UTC by Intrejan

完成合作关系描述，以及相应测试，未完成合作关系预测

2020-10-14 07:19 UTC, HermitSun commented on task-partnership-analysis/src/main/java/org/njuse17advancedse/taskpartnershipanalysis/controller/TaskPartnershipAnalysisController.java
> +@RestController(value = "/partnership")
这里的value是什么意思呢，我好像没见过这种写法？

2020-10-14 07:19 UTC, HermitSun requested changes
调用`/partnership/1/2019/2020`会报空指针异常

2020-10-14 08:13 UTC, HermitSun commented on task-partnership-analysis/src/main/java/org/njuse17advancedse/taskpartnershipanalysis/controller/TaskPartnershipAnalysisController.java
> +    value = "/partnership/{id}/{startDate}/{endDate}",
这里的URL设计可能不太符合REST的风格，因为日期是一个查询条件，并不是一个实体。
我个人认为URL应该改成类似于`/partnership/1?start=2019&end=2020`这种。
另外如果`/partnership`是一个公共前缀，不妨在整个类外面放一个`@RequestMapping`来映射整个这一块的URL。

2020-10-15 09:35 UTC, HermitSun commented on task-partnership-analysis/src/main/java/org/njuse17advancedse/taskpartnershipanalysis/controller/TaskPartnershipAnalysisController.java
> +  private ResponseEntity<HashMap<String, Double>> getPotentialPartners(
这里不应该返回HashMap，应该返回Map；接口不应该暴露实现。

2020-10-15 09:36 UTC, HermitSun requested changes
顺便稍微写一下注释

2020-10-15 10:07 UTC, Intrejan commented
是的，目前这个第二个方法返回的map就是包含可能与该作者合作的其他学者和可能程度（double类型数值）。

2020-10-15 10:35 UTC, HermitSun approved these changes
下次记得写注释，这两个方法光看名字可能不具有足够的辨识度

2020-10-15 10:35 UTC, merged