实体服务增加异常处理，修复引用分析bug
NJU-SE-17-advanced-se/backend pull request #57
Opened 2020-11-05 06:55 UTC by Tdycwym

2020-11-05 15:03 UTC, HermitSun requested changes
引用分析传入不存在的 id 会报错500。
底层如果没有抛出异常而是返回null，上层也应该处理一下。
另外，三层嵌套的循环能否优化？

2020-11-07 06:19 UTC, HermitSun commented on entity-affiliation/src/main/java/org/njuse17advancedse/entityaffiliation/service/impl/AffiliationServiceImpl.java
> +      return repository.getAffiliationById(id);
此处并没有抛出异常，只是null，所以catch没有发挥作用

2020-11-07 06:33 UTC, Tdycwym commented on entity-affiliation/src/main/java/org/njuse17advancedse/entityaffiliation/service/impl/AffiliationServiceImpl.java
> +      return repository.getAffiliationById(id);
返回值是List的查询不会出现异常（除非数据库被修改），只有返回一整个实体的方法可能出现异常。

2020-11-07 06:34 UTC, Tdycwym commented on entity-affiliation/src/main/java/org/njuse17advancedse/entityaffiliation/service/impl/AffiliationServiceImpl.java
> +      return repository.getAffiliationById(id);
返回值是List的查询不会出现异常（除非数据库被修改），只有返回一整个实体的方法可能出现异常。
在repository进行了判断，是否表中存在该键，不存在的话返回空实体。
如果出现其他奇奇怪怪的异常也可以用这个trycatch捕获到。

2020-11-07 07:10 UTC, HermitSun commented on entity-affiliation/src/main/java/org/njuse17advancedse/entityaffiliation/service/impl/AffiliationServiceImpl.java
> +      return repository.getAffiliationById(id);
我的意思是现在查询不存在的 id 还是会返回 null，并没有返回空实体。
正常情况应该是正常的实体，异常情况按理来说是抛出具有语义的异常。比如：
```
@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "找不到该数据")
public class NotFoundException extends Exception {}
```
因为异常规范暂时还没有确定，空实体只是一个暂时的折中方案。

2020-11-07 07:20 UTC, Tdycwym commented on entity-affiliation/src/main/java/org/njuse17advancedse/entityaffiliation/service/impl/AffiliationServiceImpl.java
> +      return repository.getAffiliationById(id);
我再确认一下，应该是不存在也会返回空实体

2020-11-07 07:32 UTC, HermitSun commented on entity-affiliation/src/main/java/org/njuse17advancedse/entityaffiliation/data/AllRepository.java
> +      return new IAffiliation();
这一行没法编译

2020-11-07 07:38 UTC, HermitSun commented on entity-affiliation/src/main/java/org/njuse17advancedse/entityaffiliation/service/impl/AffiliationServiceImpl.java
> +      return repository.getAffiliationById(id);
不存在先返回空实体吧，后面我定一个异常的规范

2020-11-07 08:26 UTC, HermitSun approved these changes
感谢

2020-11-07 08:27 UTC, merged